# Generated by Django 4.2.3 on 2023-07-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ditterapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dweet",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
