# Generated by Django 4.2.3 on 2023-07-19 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ditterapi", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name="author",
            name="display_name",
            field=models.TextField(
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^.{3,50}$",
                        message="Display names have to between 3 and 50 characters in length",
                    )
                ],
            ),
        ),
    ]
