# Generated by Django 4.2.3 on 2023-07-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ditterapi", "0002_alter_dweet_created_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dweet",
            name="content",
            field=models.TextField(max_length=300),
        ),
    ]
